---
- name: Download Helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 775
  register: download

- name: Instalando o Helm
  shell:
    /tmp/get_helm.sh
  register: install_helm